const config = {
    hybrisLocalSetupGuide: [
      {
        textContent1:"This guide is to help you to setup Hybris 2211 in local. It will setup OOTB hybris ecommerce sites.",
        textContent2:`Please note hybris project setup step's may vary when you work on the actual project in a company but the core concepts going to be same.
        The given steps are for MacOS.`,
        textContent3: `
        <b>Steps 1.</b> Download SAP Commerce Cloud Suite 2211<br />
        Download the suite from SAP official site or please ask your employer to provide you the suite
        . SAP commerce cloud is not open source, it is protected with license. <br/>
        <b>Steps 2.</b> Download and install JDK<br />
        Download openJdk from <a href="https://sap.github.io/SapMachine/" target='_blank' rel='noopener noreferrer'>https://sap.github.io/SapMachine/</a>. Please select options as below and click on download button. SAP Commerce cloud 2211 need atleast JDK 17.`,
        textContent4:`You can also use oracle JDK but SAP recommends to use above JDK for better compatibility.
        After installing openJdk please double check the version using command "java -version".<br/>`,
        textContent5:`<b>Steps 3.</b> Unzip the suite and extract all the files to a folder. I have created a new folder "hybris_2211" inside that lets extract the suite. It should have below structure. 
        Please have a closer look at the folder structure, you will notice inside hybris folder only bin folder exists.`,
        textContent6:`<b>Steps 4.</b> Open terminal and navigate to /hybrisroot-folder/installer i.e. /hybris_2211/installer folder and trigger command "./install.sh -r cx setup -A initAdminPassword=nimda". nimda is password, you can change it if you want. Hit enter button and wait for it to complete. Please make sure you do not stop it inbetween. This command will setup the platform.<br/>
        install.sh : It's a command which executes corresponding groovy script to setup the platform.<br/>
        -r : represents recipe<br/>
        cx : is recipe name. ./install.sh -l will give you the list of recipes which hybris provides OOTB.<br/>
        -A : is for additional parameter<br/>
        initAdminPassword : is attribute to set admin password.`,  
        textContent7:'Once it is successful you should see the build successful message in terminal as below.',
        textContent8:`<b>Steps 5.</b> Please execute "./install.sh -r cx initialize -A initAdminPassword=nimda"<br/>
        initialize : initialize the platform<br/>`,
        textContent9 :`On successful initialization you would see success message at terminal as below. Initilization takes time so be patience. For me it took around 2 hours.`,
        textContent10 :`<b>Steps 6.</b> Please execute "./install.sh -r cx start" to start the platform.<br/>`,
        textContent11 :`"INFO: Server startup in 818893 ms". 818893 is time in milliseconds, server took to start. Again time may vary for individual.`,
        textContent12 :`<b>Steps 7.</b> Congratulations!!! Server started successfully.<br/>
        Sites are accessible on below urls:<br/>
        <a href="https://localhost:9002/yacceleratorstorefront/?site=electronics&clear=true" target='_blank' rel='noopener noreferrer'>https://localhost:9002/yacceleratorstorefront/?site=electronics&clear=true</a> <br/>
        <a href="https://localhost:9002/yacceleratorstorefront/?site=apparel-uk&clear=true" target='_blank' rel='noopener noreferrer'>https://localhost:9002/yacceleratorstorefront/?site=apparel-uk&clear=true</a> <br/>
        As a part of recipe installation, Hybris will configure multiple sites. These all sites are mostly production ready. You can visit /hybris_2211/config/local.properties file to check the url of other sites.`,
        textContent13 :`We are done with site setup using recipe, lets see the changes in folder structure.<br/>
        <ul><li>inside /hybris_2211/hybris/ other folders also created e.g. config, data, log etc.</li>
        <li>inside /hybris_2211/hybris/bin/ custom folder is created. Custom folder is very important.</li>
        <li>inside /hybris_2211/hybris/config/local.properties and localextensions.xml files are created.</li></ul>` ,
        textContent14 :`Inside custom folder yacceleratorstorefront is created. yacceleratorstorefront we call this as storefront. A storefront can have multiple sites.
        This storefront is generated by hybris using recipe. Let's create our own storefront. Please stop the server by pressing ctrl+c keys. <br/>
        Delete folder yacceleratorstorefront from custom folder.<br/>
        Open /hybris_2211/hybris/config/localextension.xml with any text editor and remove <extension name='yb2bacceleratorstorefront' /> entry.<br/>
        <b>Steps 8.</b> Open new terminal or navigate to /hybris_2211/hybris/bin/platform/ and trigger command ". ./setantenv.sh"`,
        textContent15 :`<b>Steps 9.</b> Trigger command "ant modulegen" . Please keep an eye on terminal it will
        ask few details in between.`,
        textContent16 :`<b>Steps 10.</b> Please press enter key`,
        textContent17 :`<b>Steps 11.</b> I have passed kshitijtechno. You can write anytext here. Please don't give any spaces. This will be treated as storefront name. You can also press enter key without passing any value, hybris will create default training storefront.`,
        textContent18 :`<b>Steps 12.</b> I have passed org.kshitijtechno. This will be the package name used in the classes. The default package name org.training will be used if you pass empty here.`,
        textContent19 :`<b>Steps 13.</b> On completion of "ant modulegen" command, we should see below instructions in terminal. Please follow on screen instructions carefully.`,
        textContent20 :`I have added generated extensions details in my localextension.xml`,
        textContent21 :`Please remove these extensions from your properties. Otherwise it will give build errors.`,
        textContent22 :`<b>Steps 14.</b> Please run command "ant". It will build the storefront.`,
        textContent23 :`<b>Steps 15.</b> After "ant" successfully executes. Run command "./hybrisserver.sh"<br/>
        If you want to debug the Java code you should run command "./hybrisserver.sh debug"`,
        textContent24 :`Server started successfully!!! You can access new storefront at urls :<br/>
        <a href="https://localhost:9002/kshitijtechnostorefront/?site=electronics&clear=true" target='_blank' rel='noopener noreferrer'>https://localhost:9002/kshitijtechnostorefront/?site=electronics&clear=true</a> <br/>
        <a href="https://localhost:9002/kshitijtechnostorefront/?site=apparel-uk&clear=true" target='_blank' rel='noopener noreferrer'>https://localhost:9002/kshitijtechnostorefront/?site=apparel-uk&clear=true</a> <br/>`,
        textContent25 :`<b>If you face any difficulities during following the guide please drop an email to codingcrust@gmail.com. I will be happy to assist you. Thankyou so much !!!</b>`,
        textContent26 :`Hybris has created new folder inside custom folder called "kshitijtechno" and inside it has created 7 extension to support site functionality. We will modify the custom folder contents during the development.`,
        textContent27 :`<b>Steps 16.</b> You can access HAC (Hybris administration console) at url:<br/>
        <a href="https://localhost:9002/hac" target='_blank' rel='noopener noreferrer'>https://localhost:9002/hac</a> <br/>
        Use username "admin" and password "nimda" to login.`,
        textContent28 :`<b>Steps 17.</b> You can access Backoffice at url:<br/>
        <a href="https://localhost:9002/backoffice/login.zul" target='_blank' rel='noopener noreferrer'>https://localhost:9002/backoffice/login.zul</a> <br/>
        Use username "admin" and password "nimda" to login.`,      
      },
    ],
    hybrisInterviewQA: [
      {
        question: "What is SAP Hybris?",
        answer: "SAP Hybris or later renamed as SAP Commerce cloud is an e-commerce, digital marketing solution. It's owned by SAP.",
      },
      {
        question: "What is current version of SAP Commerce cloud?",
        answer: "Current version is 2211.",
      },
      {
        question: "Is SAP Commerce cloud is free to use?",
        answer: "No its not free. We should have license to use it.",
      },
      {
        question: "How we can learn SAP Commerce cloud development or Hybris development?",
        answer: `To learn the development, nowadays lots of contents are available on Internet. 
        But you can't do hands-on until you have "Hybris Suite". Usually companies who works on the Hybris projects they will purchase the license from SAP
        and will give access of suite to their employees.`,
      },
      {
        question: "What is e-commerce solution?",
        answer: "E-commerce is a platform where end user can place the orders. Customer could be a retail customer, business customer etc.",
      },
      {
        question: "What are the examples of e-commerce solutions?",
        answer: "Amazon, Flipkart, Nayka, Meesho, Taka Cliq are some examples of e-commerce solutions.",
      },
      {
        question: "SAP Commerce cloud is based on what programming language?",
        answer: "It's based on Java programming language. SAP commerce cloud uses Spring framework.",
      },
      {
        question: "SAP Commerce Cloud uses which database?",
        answer: "It uses HSQL database OOTB(Out of the box). It also support different databases like Oracle, MySql etc. We can specify database related configurations inside local.properties file.",
      },
      {
        question: "SAP Commerce Cloud uses which server?",
        answer: "It uses Apache tomcat OOTB.",
      },
      {
        question: "SAP Commerce Cloud uses which search engine?",
        answer: "It uses Apache Solr search engine.",
      },
      {
        question: "What is difference between SAP Hybris and SAP Commerce Cloud?",
        answer: "Both are same. SAP Hybris is renamed as SAP Commerce Cloud.",
      },
      {
        question: "What is items.xml?",
        answer: `items.xml is an xml file. It holds items definition for entire application. Usually it resides inside core extensions resources folder.
        Standard naming convention for the file is *extensionname*-items.xml e.g. core-items.xml. Here "core" is the extension name. Below is the structure of items.xml`,
        code:`        <items>
          <atomictypes>
            <atomictype class="java.lang.Object" autocreate="true" generate="false"/>
            <atomictype class="java.lang.Integer" extends="java.lang.Number" autocreate="true" generate="false"/>
            <atomictype class="java.lang.String" extends="java.lang.Object" autocreate="true" generate="false"/>
          </atomictypes>
          <collectiontypes>
            <collectiontype code="ExampleCollection" elementtype="Item" autocreate="true" generate="false" type="list"/>
            <collectiontype code="DeliveryModeCollection" elementtype="DeliveryMode" autocreate="true" generate="false" type="set"/>
            <collectiontype code="MediaCollection" elementtype="Media" autocreate="true" generate="false"/>
            <collectiontype code="AadharNumberCollection" elementtype="java.lang.Number" autocreate="true" generate="false"/>
          </collectiontypes>
          <enumtypes>
            <enumtype code="TestEnum">
              <value code="testValue1"/>
              <value code="testValue2"/>
            </enumtype>
            <enumtype code="CredtiCardType">
              <value code="amex"/>
              <value code="visa"/>
              <value code="master"/>
            </enumtype>
          </enumtypes>
          <maptypes>
            <maptype code="ExampleMap"
                     argumenttype="Student"
                     returntype="java.lang.Integer"
                     autocreate="true"
                     generate="false"/>
            <maptype/>
          </maptypes>
          <relations>
            <relation code="OrderDiscountRelation" autocreate="true" generate="false" localized="false"
              deployment="com.wardhan.techno.OrderDiscountRelation">
              <sourceElement qualifier="orders" type="AbstractOrder" cardinality="many" ordered="false">
                <modifiers read="true" write="true" search="true" optional="true"/>
              </sourceElement>
              <targetElement qualifier="discounts" type="Discount" cardinality="many" ordered="true"
                collectiontype="list">
                <modifiers read="true" write="true" search="true" optional="true"/>
              </targetElement>
            </relation>
          </relations>
          <itemtypes>
            <itemtype code="Customer" extends="User" jaloclass="de.hybris.platform.jalo.user.Customer" 
              autocreate="true" generate="true">
              <deployment table="Customer" typecode="31000"/>
              <attributes>
                <attribute autocreate="true" qualifier="customerId" type="java.lang.String">
                  <modifiers read="true" write="true" search="true" optional="true"/>
                  <persistence type="property"/>
                </attribute>
              </attributes>
            </itemtype>
          </itemtypes>
        </items>`,
      },
      {
        question: "Name the basic tags used in items.xml",
        answer: `atomictypes, collectiontype, enumtypes, maptypes, relations, itemtypes
        <p>"items" is the root tag for items.xml. These tags are fixed and we cannot change the sequence of the tags.          
        To remember the sequence of the tags you can use formula "ACE MRI".  
        XSD(XML schema definition) is items.xsd. Please do check this file for better understanding`,
      },
      {
        question: "Explain atomictype.",
        answer: `An AtomicType represent a simple java object. The name ('atomic') means 'non-composed' objects.
        <p>Object, Number, Integer, Boolean, String, Map are the example of atomic type.`,
      },
    ],  
    hybrisProjectImportIntellij : [
      {
        textContent1 : "These instructions are for IntelliJ IDEA 2021.3.2 (Community Edition).",
        textContent2 : `Once you are done with the local setup of SAP Commerce Cloud you 
        should import the project into intellij for development purpose. If you don't know how to do local setup
        you can follow below guide and come back to this post later.`,
        textContent3 :`<b>Steps 1.</b> Download and install intellij from official site <a href="https://www.jetbrains.com/idea/download/?section=mac">Jetbrains</a>. Download the community version only. Ultimate gives 30 days trial post trial you need to pay.<br/>
        On successful installation you will see below screen when you open it first time. Click on plugins.`,
        textContent4 :`<b>Steps 2.</b> Search "sap commerce", from results install 
        "SAP Commerce Developer Toolset". Post plugin installation IDE will ask you to restart. Click on restart IDE.<br/>
        After restart you will see above interface again. `,
        textContent5 : `<b>Steps 3.</b> Click on Projects -> New Project -> select Empty Project ->
        give any project name -> give any project location (here intellij will create workspace. It's not related to hybris) -> click on Finish. After finish it will open new intellij window.`,
        textContent6 : `<b>Steps 4.</b> Click on File -> New -> Project From Existing Sources`,
        textContent7 : `<b>Steps 5.</b> Navigate to your hybris project bin folder and select bin folder click on open button.`,
        textContent8 : `<b>Steps 6.</b> Select import project from external model radio button, select hybris and then click next button.`,
        textContent9 : `<b>Steps 7.</b> Click Next, Next 2 times until you get below screen. Select checkbox highlight with red color rectangle. With this you will be able to see the OOTB source code.`,
        textContent10 : `<b>Steps 8.</b> Select all or leave as is, click next.`,
        textContent11 :`<b>Steps 9.</b> As hybris 2211 need Java 17 mininum. So select Java 17 and click on Finish. If its not present in the list, you can click on "+" icon. Your system should 
        have OpenJdk 17.`,
        textContent12 : `<b>Steps 10.</b> Click New window`,
        textContent13 : `<b>Steps 11.</b> Now wait it will load the project structure. Intellij takes sometime to load all the files. You should wait until intellij index over. Please see red highlight area in below image.`,
        textContent14 :`<b>Steps 12.</b> If you are getting low memory error or intellij is hanged due to low memory. Please increase the heap memory for intellij to work smoothly.`,
        textContent15 :`<b>Steps 13.</b> To increase the heap memory click on lens icon -> search memory -> select Change Memory Settings`,
        textContent16 : `<b>Steps 14.</b> Increase the memory as per your system. I have increased it to 4056 from 1024 MB. Click on Save and restart.`,
        textContent17 : `<b>Steps 15.</b> Project import is completed. In intellij you must see below folder/file structure.`,
      },
    ],
    hybrisDataModeling : [
      {
        textContent1 :`<b>In SAP Commerce Cloud, Data modeling is a way to create model classes, Collections and Relations. Data modeling
        is related to the persistance layer.</b>
        <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Let's take an example of basic Java project 
        where we need to store the Student details like id, name, address inside db. 
        If we are using Hibernate, we have to create the pojo class for Student. 
        We have to write id, name, address as member variable of class along with the setters/getters</p>
        <p>But in Hybris we don't need to manually write the classes instead we have to give the details inside items.xml file and build the platform.
        Hybris will automtically generate the Student Model for you.
        So the process of defining the details inside items.xml is called Data modeling.</p>
        Data modeling is a crucial part for Hybris application. Mastering the data modeling is very much needed to work on Hybris.
        Also this is the hot topic for interviewers. Let's deep dive into Data modeling concept's.<br/>
        Below is items.xml for kshitijtechno hybris project.<br/>
        <b>kshitijtechnocore-items.xml</b> is where we have to define our Student itemtype. In Hybris we will call Customer model as Customer itemtype.<br/>
        items.xml resides inside the coreextension/resources folder of the project. For kshitijtechno, kshitijtechnocore is the core extension.`,
        textContent2 :`We have another core-items.xml inside platform. This is provided by Hybris OOTB to support the electronics and apparel store functionalities.
        During development you should not modify this core-items.xml instead modify which exists inside custom folder. 
        But you can checkout the file for reference purpose and see how SAP has defined items and what are the various available attribute which we can apply to an item.`, 
        textContent3 : `For items.xml schema is defined inside items.xsd.<br/>
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;The tags used inside items.xml to represent the data are : 
        items, atomictypes, collectiontypes, enumtypes, maptypes, relations, itemtypes.
        The sequence of the tags is fixed. For e.g. collectiontypes can't be defined after relations.
        collectiontypes should be defined after atomictypes and before enumtypes only. To easily remember the sequence you can remember word <b>"ACE MRI"</b>. Here each alphabet represent a tag.
        Also inside each main tag there is immidiate child tag. Keep remember main tag is always in plural and child tag is singular. e.g. collectiontypes is main tag, collectiontype is child tag inside collectiontypes.<br/>
        <b>items.xml is case sensitive.</b><br/>
        <b>items is the root tag for items.xml.</b><br/>
        <b>A</b> - atomictypes : atomictypes are used to represent the simple Java object. The name ('atomic') means 'non-composed' objects. e.g.
        Object, Number, Integer, Boolean, String, Map. All primitive types, wrapper class are kind of atomictype in hybris. In realtime project will rarely define any atomic types. 
        Whatever we need those are already defined by Hybris.
        Below is the code snippet.<br/>`,
        code1 : `<atomictypes>
    <atomictype class="java.lang.Object" autocreate="true" generate="false"/>
    <atomictype class="java.lang.Number" extends="java.lang.Object" autocreate="true" generate="false"/>
    <atomictype class="java.lang.Integer" extends="java.lang.Number" autocreate="true" generate="false"/>
</atomictypes>`,
        textContent4 : `atomictypes : its parent tag.<br/>
        atomictype : its child tag.<br/>
        class : it's a mandatory attibute. A Java class should be assigned to this attirbute.<br/>
        autocreate : If it's true atomictype will be created during initialization. It's optional and default value is true.<br/>
        generate : it's deprecated now. Has no effect on the atomictype`,
        textContent5 : '<b>What if we redefined the atomictype again in my custom folders kshitijtechnocore-items.xml?' , 
        textContent6 : `Build will fail. Build will through an java.lang.IllegalArgumentException due to duplicate type code.<p></p>
        <b>C</b> - collectiontypes : its used to define the collection object.`,
      },
    ],
    hybrisQuiz1 : [
      {
        question : "What is hybris?",
        answers : [`Hybris is a programming language`, 
        "Hybris is an ERP tool", "Hybris is JavaScript based library", "Hybris is an e-commrce solution"],
        correctAnswer : "Hybris is an e-commrce solution",
      },
      {
        question : "Who owns Hybris?",
        answers : ["TCS", "SAP", "Tech Mahindra", "Hybris"],
        correctAnswer : "SAP",
      },
      {
        question : "Select which is True.",
        answers : ["Hybris is renamed as SAP Commerce Cloud", "Hybris owned by TCS", "Hybris is a ERP"],
        correctAnswer : "Hybris is renamed as SAP Commerce Cloud",
      },
      {
        question : "SAP Commerce Cloud was invented in which year?",
        answers : ["1997", "1992", "1967", "2002"],
        correctAnswer : "1997",
      },
      {
        question : "What is the full form of HAC?",
        answers : ["Hybris Administration Console", "There is no full form"],
        correctAnswer : "Hybris Administration Console",
      },     
    ],
  };
  
export default config;